Update patch set 5
Patch Set 5:

Guys, I'm getting this.
Any help would be appreciated!


Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: there were 4 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)
Error: Please correct the above warnings first.

Patch-set: 5
Reviewer: LorD ClockaN <1458@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0